### ISSUE TITLE
open bmclapi

### ISSUE THREAD

**Issue by 8MiYile** [SDU-Mirrors/wonderful-github-releases#1]
npm版本 https://github.com/bangbang93/openbmclapi
go版本 https://github.com/KpnmServer/go-openbmclapi

镜像内容非项目本体 而项目下载下来的内容 那个才是需要镜像的内容

**Comment by SadPencil** [comment]
两个项目均不包含LICENSE，因此无法得知是否为开源软件，以及公众是否有权利进行分发。

bangbang93/openbmclapi 这个项目的[网站](https://bmclapidoc.bangbang93.com/)上提到

> BMCLAPI和BMCL不同，属于非开源项目

因此，我们大概无权镜像这些项目。
