### ISSUE TITLE
mingw build recommandation

### ISSUE THREAD

**Issue by zhullyb** [SDU-Mirrors/wonderful-github-releases#11]
https://github.com/niXman/mingw-builds-binaries/releases

This repository is also recommanded by mingw-w64.org

https://www.mingw-w64.org/downloads/#mingw-builds

**Comment by SadPencil** [comment]
https://www.mingw-w64.org/changelog/

https://github.com/niXman/mingw-builds-binaries/releases

I am not familiar with GCC on Windows but why the version number of this github release is higher than official change log's?

**Comment by zhullyb** [comment]
gcc version is 12.2.0 and mingw version is 10.0.0, they are not the same thing.
mingw include gcc

zhullyb
________________________________

**Comment by zhullyb** [comment]
![图片](https://user-images.githubusercontent.com/43305366/236654439-75b7e3e7-7fce-4d20-b9e2-d7da84200d80.png)

https://www.mingw-w64.org/downloads/

**Comment by SadPencil** [comment]
Completed via d47b0a5df07c7f8be375730e24a6ff2ac2673d03
