### ISSUE TITLE
请求添加新的开源软件

### ISSUE THREAD

**Issue by DroidKali** [SDU-Mirrors/wonderful-github-releases#12]
请求添加新的开源软件

[localsend/localsend](https://github.com/localsend/localsend)  免费、开源、跨平台的文件传输工具

[alist-org/alist](https://github.com/alist-org/alist)  一个支持多种存储，支持网页浏览和 WebDAV 的文件列表程序，由 gin 和 Solidjs 驱动

[NickeManarin/ScreenToGif](https://github.com/NickeManarin/ScreenToGif)  开源的GIF动图录制工具

[Genymobile/scrcpy](https://github.com/Genymobile/scrcpy)  开源安卓手机投屏控制工具

[snowie2000/mactype](https://github.com/snowie2000/mactype)  开源Windows字体美化工具

[Chuyu-Team/Dism-Multi-language](https://github.com/Chuyu-Team/Dism-Multi-language)  DISM++开源的Windows优化辅助工具

[obsidianmd/obsidian-releases](https://github.com/obsidianmd/obsidian-releases)  强大的开源笔记软件

**Comment by SadPencil** [comment]
由于基于 Electron 的软件的二进制文件数量过多过大且有明显重复浪费的情况，我们需要综合结合软件大小、流行程度等因素考虑。这些工作将会在学生考试周结束之后进行。

**Comment by DroidKali** [comment]
好的，感谢🙏🏻

**Comment by lwzhenglittle** [comment]
[localsend/localsend](https://github.com/localsend/localsend)

[NickeManarin/ScreenToGif](https://github.com/NickeManarin/ScreenToGif)

[Genymobile/scrcpy](https://github.com/Genymobile/scrcpy)

[snowie2000/mactype](https://github.com/snowie2000/mactype)

[Chuyu-Team/Dism-Multi-language](https://github.com/Chuyu-Team/Dism-Multi-language)  

以上五个软件已经添加到同步列表。

[alist-org/alist](https://github.com/alist-org/alist)  有被滥用的风险，暂时不予同步。

[obsidianmd/obsidian-releases](https://github.com/obsidianmd/obsidian-releases)  为闭源商业软件，对其进行镜像并不符合其许可协议。
