### ISSUE TITLE
minecraft open source servers

### ISSUE THREAD

**Issue by 8MiYile** [SDU-Mirrors/wonderful-github-releases#2]
SpigotMC: https://hub.spigotmc.org/stash/projects/SPIGOT
MohistMC:  https://github.com/MohistMC/Mohist

**Comment by Big-Cake-jpg** [comment]
And CatServer: https://github.com/Luohuayu/CatServer

**Comment by SadPencil** [comment]
本仓库只受理针对 GitHub Release 发布的软件的镜像请求。
- SpigotMC：非 GitHub 软件
- MohistMC：不在 GitHub Release 上发布二进制安装包
- CatServer：是否为优秀工具软件，能否给广大用户带来帮助，需要进一步考量
