### ISSUE TITLE
Microsoft Powertoys & Visual Studio Code

### ISSUE THREAD

**Issue by Big-Cake-jpg** [SDU-Mirrors/wonderful-github-releases#3]
Powertoys: https://github.com/microsoft/powertoys
一个MIT开源的，用于最大化生产力的小工具
Visual Studio Code: https://github.com/microsoft/vscode
一个强大、轻量的代码编辑器

**Comment by SadPencil** [comment]
VSCode 的官方安装包并非开源软件，我们无权镜像。
已添加 Powertoys。
