### ISSUE TITLE
Dev-Sidecar

### ISSUE THREAD

**Issue by Big-Cake-jpg** [SDU-Mirrors/wonderful-github-releases#4]
Dev-Sidecar: https://github.com/docmirror/dev-sidecar
一个效果明显的 GitHub 加速软件 & DNS 优选blabla之类的

**Comment by SadPencil** [comment]
看起来不错，但是因为这个项目众所周知的风险，尤其是《网络数据安全管理条例（征求意见稿）》第四十一条和第六十六条，我们没法镜像这个软件。
