### ISSUE TITLE
marktext recommandation

### ISSUE THREAD

**Issue by zhullyb** [SDU-Mirrors/wonderful-github-releases#6]
a markdwon editor
https://github.com/marktext/marktext/
MIT License
30k stars

**Comment by SadPencil** [comment]
发 issue 之前先看一下仓库的文件内容。

**Comment by zhullyb** [comment]
> 发 issue 之前先看一下仓库的文件内容。

在仓库的 README 中写到

> 可通过 issues 推荐更多的软件。

所以我来推荐了 marktext 这款开源的 markdown 编辑器，有什么不妥的地方嘛？

**Comment by SadPencil** [comment]
> 所以我来推荐了 marktext 这款开源的 markdown 编辑器，有什么不妥的地方嘛？

https://github.com/SDU-Mirrors/wonderful-github-releases/blob/main/repos.yaml

**Comment by zhullyb** [comment]
我的问题

zhullyb
________________________________
