### ISSUE TITLE
Mem Reduct

### ISSUE THREAD

**Issue by Big-Cake-jpg** [SDU-Mirrors/wonderful-github-releases#7]
一个轻量（ 300 KB ）的内存清理工具
https://github.com/henrypp/memreduct
效果很明显，实测我之前 8 GB  RAM 的 Windows 10 1909 使用以后内存能压到 30% 以下，Windows 11 能压到 60% 以下

**Comment by SadPencil** [comment]
Closed via 75b783998abed334180e7fc1a295ef8efb0817ab
