### ISSUE TITLE
ungoogled-chromium-android

### ISSUE THREAD

**Issue by zhullyb** [SDU-Mirrors/wonderful-github-releases#8]
https://github.com/ungoogled-software/ungoogled-chromium-android

**Comment by SadPencil** [comment]
看起来像是 Eloston/ungoogled-chromium 的 fork，在原项目更新似乎更频繁的情况下为何要选择这个 fork？（虽然它通过 GitHub Release 发行二进制）

**Comment by zhullyb** [comment]
> 看起来像是 Eloston/ungoogled-chromium 的 fork，在原项目更新似乎更频繁的情况下为何要选择这个 fork？（虽然它通过 GitHub Release 发行二进制）

看上去并不是一个fork，原项目提供 ungoogled 的 patch，适用于多个平台( Linux, Android，Windows等)，而 ungoogled-software 将其编译出来，并非 fork 关系，更像是上下游关系。

**Comment by SadPencil** [comment]
了解了
不过看起来管理有点混乱：
Windows 版的构建在 Nifury/ungoogled-chromium-binaries，该项目显示 fork 自 ungoogled-software/ungoogled-chromium-binaries
Android 版的构建如你所贴，在 ungoogled-software/ungoogled-chromium-android，该项目显示 fork 自 wchen342/ungoogled-chromium-android

项目的 Release 的更新频率似乎有点乱

我再观察一下

**Comment by SadPencil** [comment]
[ungoogled-software/ungoogled-chromium-android](https://github.com/ungoogled-software/ungoogled-chromium-android): The repository has been archived by the owner. It is now read-only.
