### ISSUE TITLE
推荐新的项目

### ISSUE THREAD

**Issue by wzwtt** [SDU-Mirrors/wonderful-github-releases#9]
ikarus23/MifareClassicTool：经典的安卓 NFC 读写工具。
rustdesk/rustdesk：开源的全平台远程控制软件。
flybywiresim/a32nx：开源的 Airbus A320neo 飞机机模。
musescore/MuseScore：开源、流行的音乐制谱软件。

**Comment by SadPencil** [comment]
rustdesk 添加完毕
MuseScore 以注释形式添加，考虑到占用空间较大且 MS store 中已有发行
其余暂不考虑
